// Developer Express Code Central Example:
// How to group ComboBoxEditor items
// 
// This example demonstrates how to group ComboBoxEditor items. DxEditors support
// binding to ICollectionView, so the main idea of this feature realization is the
// use of ListCollectionView. The basic logic is implemented in
// ComboBoxEditGroupingBehavior, which is attached to the editor.
// 
// You can find sample updates and versions for different programming languages here:
// http://www.devexpress.com/example=E4282

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }
    }
}
